/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeusCursosRouteImport } from './routes/meus-cursos'
import { Route as AdminModulosRouteImport } from './routes/admin_.modulos'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as ModuloIdRouteImport } from './routes/modulo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCursosRoute = MeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/admin_/modulos',
  path: '/admin/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloIdRoute = ModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/admin_/modulos': typeof AdminModulosRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comunidade'
    | '/diagnostico'
    | '/login'
    | '/meus-cursos'
    | '/admin/modulos'
    | '/curso/$slug'
    | '/modulo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comunidade'
    | '/diagnostico'
    | '/login'
    | '/meus-cursos'
    | '/admin/modulos'
    | '/curso/$slug'
    | '/modulo/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comunidade'
    | '/diagnostico'
    | '/login'
    | '/meus-cursos'
    | '/admin_/modulos'
    | '/curso/$slug'
    | '/modulo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  LoginRoute: typeof LoginRoute
  MeusCursosRoute: typeof MeusCursosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  CursoSlugRoute: typeof CursoSlugRoute
  ModuloIdRoute: typeof ModuloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-cursos': {
      id: '/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof MeusCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/modulos': {
      id: '/admin_/modulos'
      path: '/admin/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$id': {
      id: '/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof ModuloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComunidadeRoute: ComunidadeRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  LoginRoute: LoginRoute,
  MeusCursosRoute: MeusCursosRoute,
  AdminModulosRoute: AdminModulosRoute,
  CursoSlugRoute: CursoSlugRoute,
  ModuloIdRoute: ModuloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
